### ISSUE TITLE
Improvement to listening algorithm

### ISSUE THREAD

**Issue by AdityaIyer2k7** [Cyber-Dioxide/Jarvis-GPT#1]
Possibly replace `rec.listen` with `rec.listen_in_background` and use callbacks
Since `listen` is blocking and does not operate when functions like `recognise_google` are being called, it is better to use `listen_in_background`.

Further, instead of using `else if` statements, I suggest using a lookup table or (as I've implemented it) an Excel file

**Comment by Cyber-Dioxide** [comment]
Good one advice, iam gonna experiment with listen_in_background.
